apiVersion: v1
kind: Pod
metadata:
  name: astrid-fuzzing-demo-pod
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  runtimeClassName: sysbox-runc
  containers:
  - name: service-with-fuzzing-agent
    image: registry.nestybox.com/nestybox/ubuntu-focal-systemd-docker
    command: ["/sbin/init"]
    lifecycle:
      postStart:
        exec:
          command: ["/bin/bash", "-c", "sleep 30;\
                                      docker run --network host \
                                      --name runtime_fuzzer
                                      -dit -v /fuzzing:/agent/pcap:rw \
                                      -e BINARY_PATH='./pcap/afldemo' \
                                      -e KAFKA_ENDPOINT='127.0.0.1:9092' \
                                      -e FLASK_PORT='5000' \
                                      -e SERVICE_TIMEOUT='10' \
                                      -e FUZZING_AGENT_DEBUG='true' \
                                      spockuto/astrid-fuzzing-agent:latest"]
    volumeMounts:
    - name: fuzzing
      mountPath: /fuzzing
    ports:
    - containerPort: 5000
  volumes:
  - name: fuzzing
    persistentVolumeClaim:
      claimName: task-pv-claim
  restartPolicy: Never
